# Generated by Django 4.0.3 on 2022-03-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fancycity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='dsf',
        ),
    ]
