# Generated by Django 4.0.3 on 2022-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fancycity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='', max_length=128, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='2000-01-01', verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(default='', max_length=64, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(default='', max_length=64, verbose_name='lastname'),
        ),
    ]
