# Generated by Django 4.0.3 on 2022-03-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fancycity", "0003_usermodel_gender_usermodel_pin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="username2",
            field=models.TextField(default="", max_length=128),
        ),
    ]
