# Generated by Django 4.0.3 on 2022-03-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fancycity", "0003_rename_user_usermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
