# Generated by Django 4.0.3 on 2022-03-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fancycity", "0006_alter_usermodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(blank=True, default="", max_length=12, null=True),
        ),
    ]
